[tool.poetry]
name = "same-mono-private"
version = "0.1.0"
description = ""
authors = ["David Aronchick <aronchick@gmail.com>"]

[tool.poetry.dependencies]
python = "~3.8"
click = "^7"
jupytext = "^1.11.5"
pywin32 = { version = "227", platform = 'win32'}
jupyter = "^1.0.0"
Cerberus = "^1.3.4"
python-box = "^5.4.1"
dill = "^0.3.4"
requests = "^2.26.0"
azure-functions = "^1.7.2"
azure-functions-durable = "^1.1.1"
Jinja2 = "^3.0.1"
kfp = "^1.8.2"
azureml-dataprep-rslex = {version = "~1.20.2", python = ">=3.8,<3.9" }
azureml-core = {version = "^1.34.0", python = ">=3.8,<3.9"}
azureml-pipeline = {version = "^1.34.0", python = ">=3.8,<3.9p"}
"ruamel.yaml" = "0.17.4"
kubernetes = "^18.20.0"
numpy = "^1.21.2"
azureml-train-automl-client = {version = "^1.34.0", python = ">=3.8,<3.9" }
azureml-dataprep-native = "38.0.0"
tblib = "^1.7.0"
metakernel = "^0.27.5"
libcst = "^0.3.21"

[tool.poetry.dev-dependencies]
pip-tools = "^6.2.0"
pytest = "^6.2.5"
pytest-cov = "^2.12.1"
black = {version = "^21.8b0", allow-prereleases = true}
flake8 = "^3.9.2"
ipython = "^7.27.0"
mock = "^4.0.3"
pytest-virtualenv = "^1.7.0"
johnnydep = "^1.8"
build = "^0.6.1"
pip = "^21.2.4"
ipykernel = "^6.4.1"
pytest-mock = "^3.6.1"
setuptools = "^58.0.4"
wheel = "^0.37.0"
python-dotenv = "^0.19.0"


[tool.black]
line-length = 119

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "test",
]
norecursedirs = ["vendor",".venv"]
